exp_name: tmgpt

# model related
dim: 1024
depth: 24
quant_bit: 7

# training related
batch_size: 1
learning_rate: 1.0e-4
warmup_steps: 2000
weight_decay: 0.
max_grad_norm: 0.5
dropout: 0.
resume: null
grad_accum_every: 1
num_train_steps: 10000000000
val_every: 200
checkpoint_every: 2000
